module.exports = {
    SAMS: "oms_sams",
    SITE: "oms_site",
    DEPT: "oms_dept",
    PROGRAM: "oms_program",
    SUPPLIER: "oms_supplier",
    PO: "po",
    INVOICE: "invoice",
    SUPPORTING_DOC: "supporting_doc",
    SP: "submission_pkg",
    PO_VER: "po_ver",
    HAS_VERSION: "has_version",
    HAS_INVOICE: "has_invoice",
    HAS_DOC: "has_doc",
    HAS: "has",
    RUN_BY: "run_by",
    DELIM: "_",
    SP_ID: "sp_id",
    SUPPLIER_ID: "supplier_id",
    SUPPLIER_NAME: "supplier_name",
    PROGRAM_ID: "program_id",
    PROGRAM_NAME: "program_name",
    TOTAL_AMOUNT: "total_amount",
    CREATED_BY: "created_by",
    CREATED_DT: "created_dt",
    SP_STATUS: "sp_status",
    HAS_SP: "has_sp",
    CONTAINS: "contains",
    SS:"summary_sheet",
    HAS_SS:"has_ss"
}
